language: node_js
node_js: 4.5.0
cache:
  directories: node_modules
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_PACKAGE_NAME=heimdall-api-dev-$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.zip
install:
- npm install -g coveralls
- npm install -g strongloop
script:
- slc build --install
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: kZY+55jNrZPjEna8OzDPLqlNPxsmzYB24nRmM+t+FaHzyQ8HwUWjbGnEPP0qfzt+wSwufrUtAKu3TakQS3qBrxgodEVtlp/BzYNXLlgVDK/IUl7R2bheg5oiuz4BIhgXaA8fJzh1pCcq8CjCF9nRRnLH/zf7ETPhfgNsBkYOY6pi15clrJ96ELT7qLgQ+oWJnanrdSbW7Z2V7ErBxoyefKlZJvW3Irh52VN2Ohpgxrt0RGtVdAD3Rxi8901bLGeWCiffQ0zg3x9LhI6z+WdDt7W7Fi+5qe4PuoRYb7MzJZFOzZ/23AzxY8QB7tbOtSZhlI9U0veMIMO9BzjZ3Oes0rPVWM71rY9MJn0tixu7nKxywew5s6RLnBHWtJ9JbZbc/FoFmOx1Lz5k0TjZLFoTy0fSnYGKD9u9IBZojmGHiX2h8rOPKXpIJoWWdgUgtAUKp8d0NDvdVk1WcDqw7kzmDKVouA9PIf4xLeog955z0h2HR9+bq5iUpRooY2NntZzX/zOMqyE7ouKbDiNT7/MngIJfc3rlX7AjRxBktp/wrieK08nwkdhSOT9+OcwkFPI1b2yQlKzWFXzw/X9J9zKQFQpBepNoI11mQoVafMMftQ4P+QTbYR5LSOmoPuV5t1c/TsPnnGrq8JyDYE6ln5K9BuVmuOGpIbr7oIIBQrk9ZDw=
  secret_access_key: &2
    secure: PE25Glof5Jm5b5OWquwIvZCssmKYjvbU/9PJ5PHvTzDPpBRXbN+Agm5wJgP0sOZ6tmw1uMwFqCcUAiqZnwPUBs9Z8AWCmxCqnmlYMuyVJPd11M5ubzwSHymuejIXoR3nowy78pGSJEzjQUm6/gYLeg2PCitrE6Nro6vKoqqxBKyzZJQG3NuWHBOtgOFK6rkQqyezRMzv482dHb/zP7/w2d5PDLzbWmx98cqLs4Z92/Ilp6/JLUVplyd86aARv5orKeHzcARej4NiMwQSvYwjzW34d0H6wlZPS5A5Qj9rZWtKPdAouA4uGK4Dn6PVaYjJnYWQM55uxF0pAj7vBSfzHqeCB9Zq95f7dQFZNM0S5fmIh5e9DDyNWZhHixlfHCW9Lv93GUpwIFmZr7U0SlTMYIyXon/lE14Bid7LjHUmfsk3WUEmMZqVo3MFG8NOxfdG7adgYvHWV1G204VRVUGiRsuPOASV49hJyzSu0mqEO9sWYsZPh2XlBWrvZ3UTdAmo8pRcYsAZqjr/p7YLjjBrNW+ANEcsud5dZXagv1/tdtpKmVeRkt++sFAVzDPDRT3UV+kjnEMhU2W+bgWFA3wFw5AE8BT8YG4xCrJ5OjR6hTeKYs7ewbZlvpGocGIBUOJcqgSN48/PXyihgJJcGTR7DcavbElh1TE4nq8C80iDgmM=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-webapp
    branch: development
  bucket: dev-stage-webapp-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: dev-stage-webapp-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: dev-stage-webapp-app
  deployment_group: dev-stage-webapp-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: UQ8y/1HLzbSakJ4YFSZE+yv57VR/Jk2Oab8bKsO36OBM92YKdmYCZqbqesKxKhFOunBmEW2oxXGcN0TmxfCwiR3j6rPTZbsjvyH1xoK1gzrJpk8VmNMIk+LOf3n+1YoScEwFHbalz3df5UNgWd4D02H8WpiVnaNJ7gb+YoxrKYke+vfRc9Q5NKOM8XjEGX4yOfDtKwPIlvDu91jBPA//SFSMZdelVN/gmo2u7MMrE7bJd/hqzG6d53voksqCZ+J+999X6KRxXeTXww0G3rkD13azVEYciTgG96boB/xCu81wHe2gamDLk4cM2IeuBKRPzcern2aB7C2EkycL9raxchs7CGxI7wKTHM4ytOiJFNf6KPy6/BlOJZl9nD85DDTNIdBH9dS48/dmZEO/MYzecSHCquWOPsiTNEIow4sicYI4VJKOj8Zk3Fvi9w3xN2hUztS5Pd0u4AE+gKwNcljj3llkU+H1BRM6h8SZxmTIdJGBOcrN1m9YNJTk7ZEsa6HsfeUjGJuAb9XStJMHNlNU3hixmTYZqsqPp91V7Swv11WM4EVCowTJoP1l0Jo7WkTTKHC9MaJhrbJzjmFE1dHkK+qFagqWPCsFX8Su0KsXUWO/+Mm1swR59bNB1FW62V5GDVulktXaE5R6dTyCPFPMIgnhzJxoNgmwYJ8Stt0il4U=
