#####################################################
# heimdall-webapp build script for TravisCI
#
# Builds, tests, packages, and deploys the Node app
# to AWS on every code commit.
#
# author: Johnny Mohseni
#####################################################
language: node_js
node_js: 4.4.3
cache:
  directories: node_modules
env:
  global:
    - secure: ZISrC+n/GHsMXI5YoddKs78vK2WmkCCt5VYrC8cmXtx3pytDRf9hKomqxh3BpoqAQc5tBuMSS5jDIC+mxnplI4z/rORSMvo/aM2i3i33//vkKOrVDZi5buKnoaTBzQLHZHTI69xPkSk0H0lWGEZZPdYrsJ+OlSbsk+vQXq9rztg/G2Btohhk+5plW33CoorjxXl/r0V4zDC4E7eYS+2KJUJ/VOhLQcm6LafkjKM3RetWByUMz1Qy1iuhmLCuG4au4Frw7hAFHRTldGK+xsL3wER14k93rv5j7kC2fQC0zEEHHvIL0uu5kKLJOCt2qLY+nxz/mVagJb+3rP6h8NOFvwoTQ2qH8SQChjF08Sv/q1pi74IVyhburG08Ln2CtxEWpPDHH4O4XYTujhg4dw5NEjgogA8H80hVmCAD3QWQSPU8MxCfGW6JYR7/Hz08DaDoenNC6RDRrT96H9R0EWO3Cokd0WjcNfF4eXxxPCxh4HZhBGu4RQCosImTMtPNK+RQMCtZIlV9a03SBfW3+gbEcQ7t2iQLKiq9Pa1WVwLxBm0BLn+IMA9tSZ7DVsqcSIXOs32BXyU9tAuvW2zZGNNQ4GNlehz4RLZ8H77+5CJt/OGL59ipH6LcXk+PspjthZUXNt+SPGPZOfZj2MXeCXuvxd1osZecXEEgk+efsgoMCFI=
install:
  - npm install -g gulp
  - npm install -g jspm
  - npm install -g coveralls
  - npm install -g strongloop
  - cd client
  - npm install
  # GitHub Token needed to avoid GitHub API Rate Limit Thresholds
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install -y
script:
  - cd client
  - gulp build
  - cd ..
  - slc build --install
before_deploy:
  - cd client
  - rm -rf node_modules/
  - gulp clean # remove client/dist folder
  - cd ..
  - rm -rf node_modules/
  - zip -rq heimdall-webapp-1.0.0.zip *
  - mkdir -p dpl_cd_upload
  - mv heimdall-webapp-1.0.0.zip dpl_cd_upload/heimdall-webapp-1.0.0.zip
