language: node_js
node_js: 4.4.3
cache:
  directories: node_modules
env:
  global:
  - secure: n8GwYQhEkFEbioYb1Al/NwJpZUyv6KJGQXkKaQ7YCIZU89Hdwhv4EEu6Tg96wFfwTNMMgi+FT5boPo29rkoHSjmWEEd9LShKAGiKAewk4iopaxfZo2sw2df7m18q10t0F2ADKCMr7Eeu4XhySTlt7PXeg7Kop4Wm3i4j8XtrJJIcfnn9K4er38xJVK44JcCa/X3zOtt9WYLiMOt69klf6iSdnFT00/iNnqOJzfUP2o9AkF3GjofRdgaxx3Om+Eiht+Pqk74x4dysKPR/iJ689iXkEK8LIoXQx2uLNeHEVKg1moiwzGJlTG2StdABxpiFhTfbp5uGmYrKaYStawrCJ5Kd3ymprbfNFmZ23bZT//ruqzAJkU6V07/x4pLoj/qdMfsvNKPNlBNnjTrk1tdmEzJLKPzW4nK1Bj3HRQKWrtMcLCQPxzHoazAisgH5kjqQJ5hRXGuOtH9s3Cq3zJnnGEqe5/N1fWcE+8n4guN1m+kg+jZpTyfNozTQyAlsnyaaCn0IExGiE9Lj1O3NBAX56XB+pjMyPYk0KfXZRPhNabw7aBJVO2BjmMGve+zhIq8/jnclODFBBPAQVM56UezLr/unDXSfC2ccPus5pbuV6uZSe7ocf3RON6kdTW8z7bBK/0fBijV+3MLCNb2qU18WzdEwaDsXHw41eqBB85HVF7M=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_PACKAGE_NAME=heimdall-api-dev-$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.zip
install:
- npm install -g coveralls
- npm install -g strongloop
script:
- slc build --install
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: RSiHOBsASLa7n/i16kigp2o9r+DMuGnGh8zbBitxjgj2LZ0vQCBSOoLVyVeODzkw5kjwCydpllBDxswWgQciZrozWUpMCJ/E/PXrETzAQ+imeN6gqo4XPvICErn65jzNf1sW652pIUrCBpoSoefeF4Bs/4la9L0qraRiRWT3Wq2hlJiGbAq52eJIo/qf0eWGVWOiyvF6y+SFWPYzO6uwj23/Ily7zkKZRnvs+SAfme7wUcl0LNv0FtMmKKsJ+CkAnTjPupWRSQ+F15HTwul2bsvTNg4kBJlwlO9X3PYFbHR8cHiKCwpvP0ge8HfNecWFT8JSyTJZgW7YWGUJgteg3gvkpghghbtJdwnl+W3aRc5saOWRR2kp1usoVikSqcwVkDNanxW4wljMd+TKYtl+salGIGlXoqN5z6AyqyCdDyn1YlTGIwBFjAgCznsCE7HW1pQlturanYNUntSKS/wwNUL8rKPbpdcwyveBNYu8IQgTLHDrAG88wGANWYBAbv3OOCHHWIkhsDSUr96M8oQBIwrQvXDSF5xUFIPz1eu3R6dbZPzmrRU82rr2PTJWanBtxqNodHC6YCxIoS2MMViClXPZxHQGYruZpQ4/6i9fHa1Gaw+VDkY8auL2rAm0P5lY3voo3XWU3towYK3Aexx93aU4GQeAP5t0FsImgJbMzYw=
  secret_access_key: &2
    secure: i9WcyDZrrdRf3ia++tqChbDwIwiV0HE4xDxcO8nGJ5KKpV9ttwRVgFUFdjP5yxhSwZXDlP3AC6DYEKTR2RRt205vAWmYsZaxOehosj7ezLfuLqgudiTtdJpFYCUrbJ+FhOHmvsX7ZLFeFpa/ihndDeXhvfnSaUbkXpA7EEI1deoGCGuPkUQ82U/VQyRiXKjvojwzitd6I8aAr/Izh7OljaBe/KEsEgkQmzbfkIjFKyYDzNPiumHF49OzVaP+IJXFHgzPy6yGl8po9Rot6vebJ49qXwN/uQufKHHcJfD+3mckTrsVnBAA6dBlImbOUNXGQKjw3q9+op9P0YbtgwE/Iv42qL4G2dTlyLSOnrQk25t/41hbtlyP6Y8aL5mxXKNjZqawn+5i99TBavaZ2MXfsjvuiWD8//m40brqtTsvRDU8oCx60UJeAEjlSH7BkguixEtnO3V9zyTgcXCYO66nG7QgQRsYqrDh1paqktJQfA1AUASa1MZMFxpNWZmP7vOnVWjYW7Ju4pFFxgPQqMXkNEs3VYnjyrFqQLZoGrYf4j9Y4j+1X5uVe4YpPxd53wCFCB2gO4zL4UJSfbUrf6gTb0i2xPVzH8R88vmHpxirvMyIgrhHPX1DuO36i+JMJ7KJkuH7augBTD8KLPapeSIW+0WHzy2hxt/44p5d6lQa2+A=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-webapp
    branch: development
  bucket: dev-heimdall-api-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  secret_key_id: *1
  secret_access_key: *2
  bucket: dev-heimdall-api-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: dev-heimdall-api-app
  deployment_group: dev-heimdall-api-app-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: UQ8y/1HLzbSakJ4YFSZE+yv57VR/Jk2Oab8bKsO36OBM92YKdmYCZqbqesKxKhFOunBmEW2oxXGcN0TmxfCwiR3j6rPTZbsjvyH1xoK1gzrJpk8VmNMIk+LOf3n+1YoScEwFHbalz3df5UNgWd4D02H8WpiVnaNJ7gb+YoxrKYke+vfRc9Q5NKOM8XjEGX4yOfDtKwPIlvDu91jBPA//SFSMZdelVN/gmo2u7MMrE7bJd/hqzG6d53voksqCZ+J+999X6KRxXeTXww0G3rkD13azVEYciTgG96boB/xCu81wHe2gamDLk4cM2IeuBKRPzcern2aB7C2EkycL9raxchs7CGxI7wKTHM4ytOiJFNf6KPy6/BlOJZl9nD85DDTNIdBH9dS48/dmZEO/MYzecSHCquWOPsiTNEIow4sicYI4VJKOj8Zk3Fvi9w3xN2hUztS5Pd0u4AE+gKwNcljj3llkU+H1BRM6h8SZxmTIdJGBOcrN1m9YNJTk7ZEsa6HsfeUjGJuAb9XStJMHNlNU3hixmTYZqsqPp91V7Swv11WM4EVCowTJoP1l0Jo7WkTTKHC9MaJhrbJzjmFE1dHkK+qFagqWPCsFX8Su0KsXUWO/+Mm1swR59bNB1FW62V5GDVulktXaE5R6dTyCPFPMIgnhzJxoNgmwYJ8Stt0il4U=
