language: node_js
node_js: 4.5.0
cache:
  directories: node_modules
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_PACKAGE_NAME=heimdall-api-dev-$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.zip
install:
- npm install -g coveralls
- npm install -g strongloop
script:
- slc build --install
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: kID8lDfPgmRNkaT76oHqLyht27W09gj+2/lhJRw/j4OYKAxKG5TSfrFMg8nZ4csRJvSLH/ca3oyoi+lFxFkZ1N/5UbfKNI1uTi/29AxQXeRHUVqI042wKuavBVWi7XrBY8TvHooVIiZpgjfd7nj7S1ZTuayRWuHXNoUJiU/5vWFb1XmVIbmw05wyOmJuYMvpEQbviL5CLCpAosW1gPAqz/IgQKfKmO37x7NV6c2G34YcdKyVLoiTgs2vlzLDXZ+SBRduphFmmdtRhdUnS4+XsE2lz5WXuFQAdd90FfHopKB7fDyZAZMxTaW5ksfwcHCZ7kOf07+U3vRtOh7NHEvORoPaO5ckKUbUCxxAmujHVZxQArwVnRK9PolFWR8x/xnN3M9aZG5BgLJCkUhp4C1/twPhrE1aVnAw2Lc/TkYEHFvB46xTdHEjFop4510jVCGx2iA23BNIH3RATBP2Uki9+gRCxNuoVKeh46RLqCj3t+uehM3RfA+r0g+NMJCybG4wFfi/MlpP2XPAo22StBwomebntVC/0mPveq1sF2Q2VVlBxII57SfNgsWEKEa74L1UIHn79ZJiHVj3AbFB+OQXAJyS7fHkh+m0Tty+nw5/r5C1hx4UVeDVqSkAE52koJOHekLo2GTyg9L5sydfKSvhKybVuV1s5WYlUba2I/QvJrI=
  secret_access_key: &2
    secure: r7vv7I2qGjdhu2g+GhJrLaS8tsG0n+dICZ57gGJfRX6prMDMawzx0mYg98xe8K5qDb0+w17mZ+Qq145CKIqLaEUJrFrr5reTBsTJLgto9gmjeZphNr+ye8+Lahuz3uHwrA1VAZ6uxmO+07ftCak4p1FXcsEenoin0W8Cc7tsFwF64EJnXwsRGBI+oNq6YhAd/fYx1HIWphLm0qDq5Ixcr8Z9V3sufKdsAnMBOiLJHaYw/Y7vj/1chIvCZSulAvlZKwMb9KFCml0PFOPj4ifI4YLq+l+nkpsQg+npXXerPkXcKZTiPYS1q6H9Bpg4d/9yNDyPn7W84ryi6dkMzyxnX97MmEltRmiOu/g5w3V41suc5QxwMQyR2DurmnJDX6WfbVE765m8osMqI41m04qET20FcZ/yznHAqImfG9v1uwPfXgvvs5oRt62WAkGo6tnbbNLwESuJuQPHVsme/5XPuTtjZMv51MMwcPz/qcX/RwKsM7V4IGNKzKIkzObY0x0JWbMGchnLBrM9HN0Ai8v33t8jzc+9HicaITrXK6u+V0g3slYNZtPTcEayMB6SoAWQxnLnIZmLWd/O1FXWqP5qaiMAlpxKzVJiGCOSewTv4BK+K76zJU5rEm3azBAX4PdI6TlQdIh4pzz96m6GqiXZNaMwiFqf1zqCXxk/C71VePw=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-webapp
    branch: development
  bucket: dev-heimdall-api-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: dev-heimdall-api-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: dev-heimdall-api-app
  deployment_group: dev-heimdall-api-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: UQ8y/1HLzbSakJ4YFSZE+yv57VR/Jk2Oab8bKsO36OBM92YKdmYCZqbqesKxKhFOunBmEW2oxXGcN0TmxfCwiR3j6rPTZbsjvyH1xoK1gzrJpk8VmNMIk+LOf3n+1YoScEwFHbalz3df5UNgWd4D02H8WpiVnaNJ7gb+YoxrKYke+vfRc9Q5NKOM8XjEGX4yOfDtKwPIlvDu91jBPA//SFSMZdelVN/gmo2u7MMrE7bJd/hqzG6d53voksqCZ+J+999X6KRxXeTXww0G3rkD13azVEYciTgG96boB/xCu81wHe2gamDLk4cM2IeuBKRPzcern2aB7C2EkycL9raxchs7CGxI7wKTHM4ytOiJFNf6KPy6/BlOJZl9nD85DDTNIdBH9dS48/dmZEO/MYzecSHCquWOPsiTNEIow4sicYI4VJKOj8Zk3Fvi9w3xN2hUztS5Pd0u4AE+gKwNcljj3llkU+H1BRM6h8SZxmTIdJGBOcrN1m9YNJTk7ZEsa6HsfeUjGJuAb9XStJMHNlNU3hixmTYZqsqPp91V7Swv11WM4EVCowTJoP1l0Jo7WkTTKHC9MaJhrbJzjmFE1dHkK+qFagqWPCsFX8Su0KsXUWO/+Mm1swR59bNB1FW62V5GDVulktXaE5R6dTyCPFPMIgnhzJxoNgmwYJ8Stt0il4U=
