deploy:
  provider: s3
  access_key_id: E61gyYMqJ42ZFF96CrytuMworhUZMb2j9+9PKgQ1
  secret_access_key:
    secure: o7+WZ4UM0RfoaJ3JgXpydPKTitBzxxwAX8Ucg9TVRPj5D+4a2LYYMw9X+K/3cOPF0PGn7Yplk3Ta1+xOvV2XZw8SHxPdPXk3xfD8eUbapOD/q13aD3jeLkSmQsbx3GoFb7mLmh8Pb2NOIqhjUX1k9lN0ue/bfv8hQC2ZFUTO/ANvMKdBUmfa2ci3wDT5gDI5GzWo51yuL+4xzOjOfaXUi9fGsek2tR2JR39H/qu369Louhg7Ivj6LgvzPgIBj4YMW7LpNATyxE8mxmEqSaefQs9IRUI+IhkY4rbWkgLAN68l3jwXswLQKm6y5+dfgFpkGBKcp3LWBLOxV51LpxSJbpg7SGZBkD1G0Gzq9MPlFPOdV3xXR54F2veP6qe0puTNjR+RsnAmNupp77jMPDQ6liF03JyYFtpkukQjSm+OunQoJ7btHa60MXiivROucU1ukXcihH14CbrJaxuataQ0bxO2Y1sOkM0UBR/gDWBEzhfym/YK7PeJOUM2zsZkorXHUb1lcr7tiM3nYf2sco2yJxOOcqcOK76sNJDsRLj3zzd5FF+o9rilUB9uSpIk7oFxMEEyrlGNONPbDK1xN+ymlXNm3FkPRjiNYpecgR2sdgpCJt94zOmpJUK9nEfi2jIrP+nOlRpo+apfmC8Tc6/Vr3+Sw+B6qZB297mEZ2NOd4g=
  bucket: aasdf
  local-dir: asdf
  acl: ''
  on:
    repo: Project-Heimdall/heimdall-webapp
