language: node_js
node_js: 4.4.3
cache:
  directories: node_modules
env:
  global:
  - secure: n8GwYQhEkFEbioYb1Al/NwJpZUyv6KJGQXkKaQ7YCIZU89Hdwhv4EEu6Tg96wFfwTNMMgi+FT5boPo29rkoHSjmWEEd9LShKAGiKAewk4iopaxfZo2sw2df7m18q10t0F2ADKCMr7Eeu4XhySTlt7PXeg7Kop4Wm3i4j8XtrJJIcfnn9K4er38xJVK44JcCa/X3zOtt9WYLiMOt69klf6iSdnFT00/iNnqOJzfUP2o9AkF3GjofRdgaxx3Om+Eiht+Pqk74x4dysKPR/iJ689iXkEK8LIoXQx2uLNeHEVKg1moiwzGJlTG2StdABxpiFhTfbp5uGmYrKaYStawrCJ5Kd3ymprbfNFmZ23bZT//ruqzAJkU6V07/x4pLoj/qdMfsvNKPNlBNnjTrk1tdmEzJLKPzW4nK1Bj3HRQKWrtMcLCQPxzHoazAisgH5kjqQJ5hRXGuOtH9s3Cq3zJnnGEqe5/N1fWcE+8n4guN1m+kg+jZpTyfNozTQyAlsnyaaCn0IExGiE9Lj1O3NBAX56XB+pjMyPYk0KfXZRPhNabw7aBJVO2BjmMGve+zhIq8/jnclODFBBPAQVM56UezLr/unDXSfC2ccPus5pbuV6uZSe7ocf3RON6kdTW8z7bBK/0fBijV+3MLCNb2qU18WzdEwaDsXHw41eqBB85HVF7M=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_PACKAGE_NAME=heimdall-api-dev-$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.zip
install:
- npm install -g coveralls
- npm install -g strongloop
script:
- slc build --install
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: YYeaDUafYZ4MSjZSNHNF3Jru3bn3bpDH4kzj4sv2GL3TZsRkEBV65ZFP050W+fBMvNk8oo0qDIVDGtSSj57Tshnu57eRXuaGBCRdVXZrkRtGzvDfk2tCnrU6er0NwWYl8jJXpmr3wnrvCBIg+OPzbHW7WqscHLvX3beFypWmcI0c7lIiG2cl0wA41iDiGDaO0gV2c9doxLvKFhS5BZS0UzXzbUHpxa/4WXSsqvgsOJDrUJ4Jk9RQSEU7cRQOkcHbdcP7WlKpP+58BEoJz1ijQoggFrHL3bxLmyNmuC9HfzE7VHOP33ShD6UrcBwfzD5BqHDZrqy9VgUsOtJLiNg8zcfINFCU9pyNDVkGxJHdNoKEp8OcIhJa+ICs2d4aPEC8J8cUq79GpvAmOgmKxcoUKRvAM6ZRuXAFuJGwjWBVbDFl30iIHX0NolvyklI1umKtMt5aRgcUTlgHEFBWier73DwIFmYSej91DEbdGFOzvEzkvaQ/qaJ4zU3bRGYFVmBj08Ma/FZg8CTI/usruz0q1ccJtlgR+ff+Wty6A39h6eMc9h24oEyBRULfQW0/6570v6kodo6rNcU5AkgSegNeKzHn8f690Y+1ekB5qsWDbzmAM1sTOoXgVFdwTNlpGJnnoHtgKUNZIhg4FpTElbAD1k9sTvVttHZ+Iznhjke32ls=
  secret_access_key: &2
    secure: NXUWkxXmjGNinScnVNrFvo0T7oLuE5Suswvc7jvPcNcYI7tG1qa6pzRIR/+0w420N+/N8bPhhbbTgVN711lFHIbdRSi362PDkWZ5QTYOAraqAeL15ElPt/u1WSbiBViTmgIREvZZQvMYf3HYrGRBwYXMsren9CqMDWygNjdffB9qR/ddv2LPI2qPtzvoXF/R/ySV86yVJeJeOQfuFlvak4COQqzo/9jECG+hKkioQxqypv9RFcBYKHaq6wjl3xdZ7jy5ZMO1SLU1OOZqoprFW9BQ2D4e9hTb5aPUHOtuydMEhlwyLqcgIP5jywD1nhhzJ4aabrY3ofmBN6VhuP8EOuBPgb6/BQs2yCg5buN/Eihv3djhwuD/Gb9U/mJryU6t6mRw3gLwe+KE30W9BE6A6b15fp8nhIvsSM2HCk6qgNcYmO38ibv75epziPkJLuHLWESLfWIRS4BNiaVRGUAO4gAPzM8CNc/61WO5I3Ma2N280irodV34w4+Fa30708V/hiV6KnwefbreX4E6+BARNhn+imRVLGmWtXb0DPn0IM5ZTp6zvRlA/JXRkiD9bR4qBUIzQzf84N8VsALrUDcdlA1I0JCRN64bf00+5y+ocNWlBZ5EYVGhLJpklY5leod60uTUqtthmnk0SrcUBwI6FkxZmFVObJL6ZdeaX3HTaRY=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-webapp
    branch: development
  bucket: dev-heimdall-api-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  secret_key_id: *1
  secret_access_key: *2
  bucket: dev-heimdall-api-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: dev-heimdall-api-app
  deployment_group: dev-heimdall-api-app-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: UQ8y/1HLzbSakJ4YFSZE+yv57VR/Jk2Oab8bKsO36OBM92YKdmYCZqbqesKxKhFOunBmEW2oxXGcN0TmxfCwiR3j6rPTZbsjvyH1xoK1gzrJpk8VmNMIk+LOf3n+1YoScEwFHbalz3df5UNgWd4D02H8WpiVnaNJ7gb+YoxrKYke+vfRc9Q5NKOM8XjEGX4yOfDtKwPIlvDu91jBPA//SFSMZdelVN/gmo2u7MMrE7bJd/hqzG6d53voksqCZ+J+999X6KRxXeTXww0G3rkD13azVEYciTgG96boB/xCu81wHe2gamDLk4cM2IeuBKRPzcern2aB7C2EkycL9raxchs7CGxI7wKTHM4ytOiJFNf6KPy6/BlOJZl9nD85DDTNIdBH9dS48/dmZEO/MYzecSHCquWOPsiTNEIow4sicYI4VJKOj8Zk3Fvi9w3xN2hUztS5Pd0u4AE+gKwNcljj3llkU+H1BRM6h8SZxmTIdJGBOcrN1m9YNJTk7ZEsa6HsfeUjGJuAb9XStJMHNlNU3hixmTYZqsqPp91V7Swv11WM4EVCowTJoP1l0Jo7WkTTKHC9MaJhrbJzjmFE1dHkK+qFagqWPCsFX8Su0KsXUWO/+Mm1swR59bNB1FW62V5GDVulktXaE5R6dTyCPFPMIgnhzJxoNgmwYJ8Stt0il4U=
